apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: timestamp-workflow
  namespace: argo
spec:
  entrypoint: whalesay
  ttlStrategy:
    secondsAfterCompletion: 3
  templates:
  - name: whalesay
    container:
      image: docker/whalesay:latest
      command: [sh, -c]
      args:
        - |
          echo "Timestamp: $(date)" | cowsay
          sleep 30
