apiVersion: argoproj.io/v1alpha1
kind: WorkflowTemplate
metadata:
  name: timestamp-workflow-template
  namespace: argo
spec:
  entrypoint: print-time
  templates:
    - name: print-time
      container:
        image: alpine:latest
        command: [sh, -c]
        args: ["echo Current timestamp: $(date)"]