apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflow-jon
  namespace: default
spec:
  destination:
    namespace: argo
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/N214/argo-cd-workflow.git
    targetRevision: HEAD
    path: workflow
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true