apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-workflow-app
  namespace: default  # Namespace where Argo CD is installed
spec:
  project: default
  source:
    directory:
      recurse: true
    path: ./workflow
  destination:
    namespace: argo  # Namespace where the workflow will be deployed
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
